# Generated by Django 2.2 on 2019-05-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='email',
            field=models.CharField(default='abc@xyz.com', max_length=100),
        ),
    ]
